export const FETCH_MOVIES_STARTED = 'FETCH_MOVIES_STARTED';
export const FETCH_MOVIES_COMPLETED = 'FETCH_MOVIES_COMPLETED';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';

export const FETCH_DETAILED_MOVIE_STARTED = 'FETCH_DETAILED_MOVIE_STARTED';
export const FETCH_DETAILED_MOVIE_COMPLETED = 'FETCH_DETAILED_MOVIE_COMPLETED';
export const FETCH_DETAILED_MOVIE_FAILED = 'FETCH_DETAILED_MOVIE_FAILED';

