export const FETCH_MOVIES_STARTED = 'FETCH_MOVIES_STARTED';
export const FETCH_MOVIES_COMPLETED = 'FETCH_MOVIES_COMPLETED';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';

export const FETCH_MOVIE_DATA_STARTED = 'FETCH_MOVIE_DATA_STARTED';
export const FETCH_MOVIE_DATA_COMPLETED = 'FETCH_MOVIE_DATA_COMPLETED';
export const FETCH_MOVIE_DATA_FAILED = 'FETCH_MOVIE_DATA_FAILED';

export const FETCH_MOVIE_DETAILS_STARTED = 'FETCH_MOVIE_DETAILS_STARTED';
export const FETCH_MOVIE_DETAILS_COMPLETED = 'FETCH_MOVIE_DETAILS_COMPLETED';
export const FETCH_MOVIE_DETAILS_FAILED = 'FETCH_MOVIE_DETAILS_FAILED';

export const FETCH_MOVIE_VIDEOS_STARTED = 'FETCH_MOVIE_VIDEOS_STARTED';
export const FETCH_MOVIE_VIDEOS_COMPLETED = 'FETCH_MOVIE_VIDEOS_COMPLETED';
export const FETCH_MOVIE_VIDEOS_FAILED = 'FETCH_MOVIE_VIDEOS_FAILED';

export const FETCH_MOVIE_POSTER_BACKDROPS_STARTED = 'FETCH_MOVIE_POSTER_BACKDROPS_STARTED';
export const FETCH_MOVIE_POSTER_BACKDROPS_COMPLETED = 'FETCH_MOVIE_POSTER_BACKDROPS_COMPLETED';
export const FETCH_MOVIE_POSTER_BACKDROPS_FAILED = 'FETCH_MOVIE_POSTER_BACKDROPS_FAILED';

